produto_index:
    path:     /
    defaults: { _controller: "AppBundle:Produto:index" }
    methods:  GET

produto_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Produto:show" }
    methods:  GET

produto_new:
    path:     /new
    defaults: { _controller: "AppBundle:Produto:new" }
    methods:  [GET, POST]

produto_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Produto:edit" }
    methods:  [GET, POST]

produto_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Produto:delete" }
    methods:  DELETE
