services:
    app.admin.pacote:
        class: AppBundle\Admin\PacoteAdmin
        arguments: [~, AppBundle\Entity\Pacote, AppBundle:PacoteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Pacote}
