AppBundle\Entity\FosGroup:
    type: entity
    table: fos_group
    uniqueConstraints:
        UNIQ_4B019DDB5E237E06:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        roles:
            type: array
            nullable: false
            length: null
            fixed: false
    manyToMany:
        user:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: group
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
